import turtle

def head():    
    turtle.color('black')    # 脸轮廓    
    turtle.fillcolor('#FFE4B5')    
    turtle.begin_fill()    # 落笔    
    turtle.pd()    # 画一个半径为指定值的圆    
    turtle.circle(50)    # 提笔    
    turtle.pu()    
    turtle.end_fill()    # 移动到指定坐标位置，参数 1 代表 x 轴位置，参数 2 代表 y 轴位置    
    turtle.goto(50, 60)    
    turtle.pd()    
    turtle.circle(25, 255)    
    turtle.pu()    
    turtle.goto(60, 80)    
    turtle.pd()    
    turtle.circle(-10, -200)    
    turtle.pu()    
    turtle.goto(-50, 60)    
    turtle.pd()    # 按逆时针改变行进方向    
    turtle.seth(180)    
    turtle.circle(-25, 255)    
    turtle.pu()    
    turtle.goto(-60, 80)    
    turtle.pd()    
    turtle.circle(10, -200)    
    turtle.pu()    # 眼睛    
    turtle.goto(10, 65)    
    turtle.seth(45)    
    turtle.pd()    
    turtle.circle(-8, 360)    
    turtle.pu()    
    turtle.goto(13, 62)    
    turtle.fillcolor('black')    
    turtle.begin_fill()    
    turtle.pd()    
    turtle.circle(-4, -360)    
    turtle.pu()    
    turtle.end_fill()    
    turtle.goto(-10, 65)    
    turtle.seth(135)    
    turtle.pd()    
    turtle.circle(8, 360)    
    turtle.pu()    
    turtle.goto(-13, 62)    
    turtle.fillcolor('black')    
    turtle.begin_fill()    
    turtle.pd()    
    turtle.circle(4, 360)    
    turtle.pu()    
    turtle.end_fill()    # 鼻子    
    turtle.goto(-6, 45)    
    turtle.seth(70)    
    turtle.fillcolor('red')    
    turtle.begin_fill()    
    turtle.pd()    
    turtle.circle(-6, 150)    
    turtle.pu()    
    turtle.end_fill()    
    turtle.goto(-6, 45)    
    turtle.seth(-70)    
    turtle.fillcolor('red')    
    turtle.begin_fill()    
    turtle.pd()    
    turtle.circle(6, 150)    
    turtle.pu()    
    turtle.end_fill()    # 嘴    
    turtle.goto(0, 40)    
    turtle.seth(270)    
    turtle.pd()    
    turtle.forward(7)    
    turtle.pu()    
    turtle.seth(200)    
    turtle.pd()    
    turtle.circle(-15, 60)    
    turtle.pu()    
    turtle.goto(0, 33)    
    turtle.seth(-20)    
    turtle.pd()    
    turtle.circle(15, 60)    
    turtle.pu()    # 牙齿    
    turtle.goto(0, 33)    
    turtle.seth(270)    
    turtle.pd()    
    turtle.forward(13)    
    turtle.seth(180)    
    turtle.forward(6)    
    turtle.seth(90)    
    turtle.forward(13)    
    turtle.pu()    turtle.goto(6, 33)    turtle.seth(270)    turtle.pd()    turtle.forward(13)    turtle.seth(180)    turtle.forward(6)    turtle.pu()    # 胡子    turtle.goto(30, 30)    turtle.seth(8)    turtle.pd()    turtle.circle(-40, 40)    turtle.pu()    turtle.goto(30, 25)    turtle.seth(-5)    turtle.pd()    turtle.circle(-40, 40)    turtle.pu()    turtle.goto(30, 20)    turtle.seth(-18)    turtle.pd()    turtle.circle(-40, 40)    turtle.pu()    turtle.goto(-30, 30)    turtle.seth(172)    turtle.pd()    turtle.circle(40, 40)    turtle.pu()    turtle.goto(-30, 25)    turtle.seth(188)    turtle.pd()    turtle.circle(40, 40)    turtle.pu()    turtle.goto(-30, 20)    turtle.seth(196)    turtle.pd()    turtle.circle(40, 40)    turtle.pu()